# Github Actions Workflow For Deploying Angular Build App to Netlify
name: GitHub Actions For Deploying Angular App Build On Netlify

on:
  push:
    branches: [Prod]
  pull_request:
    branches: [Prod]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js and NPM
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: "Install Angular CLI"
        working-directory: ./client
        run: npm install -g  @angular/cli
      - name: "Install Netlify CLI"
        run : npm install netlify-cli -g
      - name: "Install NPM Dependencies"
        working-directory: ./client
        run: npm ci
      - name: "Create Build File"
        working-directory: ./client
        run: npm run build
      - name: "Deploy Build On Netlify"
        working-directory: ./client
        env: 
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_API_TOKEN: ${{ secrets.NETLIFY_API_TOKEN }}
        run: |
          netlify deploy \
            --prod \
            --dir dist/chess \
            --site "$NETLIFY_SITE_ID"  \
            --auth "$NETLIFY_API_TOKEN"
      