# Github Actions Workflow For Deploying Angular Build App to Netlify
name: GitHub Actions For Deploying Angular App Build On Netlify

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js and NPM
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: "Run the Deploy Client CI Script"
        env: 
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_API_TOKEN: ${{ secrets.NETLIFY_API_TOKEN }}
        run: "sh ./automations/deployClientCI.sh"
      